apiVersion: v1
kind: Service
metadata:
  name: {{ include "seaweedfs-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "seaweedfs-operator.fullname" . }}
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.port.number }}
  selector:
    {{- include "seaweedfs-operator.selectorLabels" . | nindent 4 }}
