{{- if and .Values.rbac.serviceAccount.create (ne .Values.rbac.serviceAccount.name "default") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seaweedfs-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "seaweedfs-operator.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.rbac.serviceAccount.automount }}
{{- end }}
