{{- if .Values.webhook.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
    app: {{ include "seaweedfs-operator.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: webhook-server
  selector:
    {{- include "seaweedfs-operator.selectorLabels" . | nindent 4 }}

{{- end }}
