apiVersion: v2
name: seaweedfs-operator
description: A Helm chart for the seaweedfs-operator
type: application
version: 1.3.1
appVersion: "1.0.2"
maintainers:
  - name: chrislusf
    url: https://github.com/chrislusf
