apiVersion: v2
name: seaweedfs-operator
description: A Helm chart for the seaweedfs-operator
type: application
version: 1.5.6
appVersion: "1.0.2"
maintainers:
  - name: chrislusf
    url: https://github.com/chrislusf
