apiVersion: v2
name: seaweedfs-operator
description: A Helm chart for the seaweedfs-operator
type: application
version: 0.1.7
appVersion: "1.0.6"
maintainers:
  - name: chrislusf
    url: https://github.com/chrislusf
