apiVersion: v1
entries:
  seaweedfs-operator:
  - apiVersion: v2
    appVersion: 1.0.6
    created: "2025-11-30T19:59:48.614387557Z"
    description: A Helm chart for the seaweedfs-operator
    digest: 4a1e94aad41709896cb69e7a3ba7ab10869c7880c2e11721bf8c7d9e7d8eb622
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://github.com/seaweedfs/seaweedfs-operator/releases/download/seaweedfs-operator-0.1.7/seaweedfs-operator-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: 1.0.6
    created: "2025-11-29T08:07:09.513111691Z"
    description: A Helm chart for the seaweedfs-operator
    digest: dbfc4b109417c5bf5541a8bceb98b6e0479bb8c241c174c1bbde93772e3821d2
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://github.com/seaweedfs/seaweedfs-operator/releases/download/1.0.6/seaweedfs-operator-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 1.0.4
    created: "2025-07-20T07:19:48.497768195Z"
    description: A Helm chart for the seaweedfs-operator
    digest: 18e0af86db44a807e0d828f17fc35700a9b4ab35c31f9d5d220ad0008185f0ea
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-03-27T15:34:03.394564646Z"
    description: A Helm chart for the seaweedfs-operator
    digest: 9cd2079997c28efd73a220782047bf46589e762b1d7a7af9beb92d4e5e4919ad
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2024-10-17T16:46:34.202841886Z"
    description: A Helm chart for the seaweedfs-operator
    digest: b4344ef75dc3545aaf74872d5759e97e2e9b0b068d2aadf2a5d7a13eaa70198f
    maintainers:
    - name: chrislusf
      url: https://github.com/chrislusf
    name: seaweedfs-operator
    type: application
    urls:
    - https://seaweedfs.github.io/seaweedfs-operator/helm/seaweedfs-operator-0.0.2.tgz
    version: 0.0.2
generated: "2025-11-30T19:59:48.611224674Z"
